#!/bin/bash

# Update packages
sudo apt update -y

# Install required packages
sudo apt install -y unzip curl wget

####################################
# Install AWS CLI v2
####################################
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

unzip -q awscliv2.zip

sudo ./aws/install

aws --version

####################################
# Configure AWS CLI
####################################
echo "Run the following command and enter your AWS credentials:"
echo "aws configure"

####################################
# Install eksctl
####################################
ARCH=amd64
PLATFORM=$(uname -s)_$ARCH

curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_${PLATFORM}.tar.gz"

tar -xzf eksctl_${PLATFORM}.tar.gz -C /tmp

sudo mv /tmp/eksctl /usr/local/bin

eksctl version

####################################
# Install kubectl
####################################
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

chmod +x kubectl

sudo mv kubectl /usr/local/bin/

kubectl version --client

####################################
# Verify installations
####################################
echo "AWS CLI Version:"
aws --version

echo "eksctl Version:"
eksctl version

echo "kubectl Version:"
kubectl version --client

echo "Installation completed successfully!"
